server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:${ORDER_DB_PORT:5431}/${ORDER_DB_NAME:orderdb}
    username: ${ORDER_DB_USER:order_user}
    password: ${ORDER_DB_PASSWORD:order_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

example:
  property: "Development Configuration Value"