spring:
  datasource:
    url: jdbc:postgresql://localhost:${ORDER_DB_PORT:5431}/${ORDER_DB_NAME:orderdb}
    username: order_user
    password: {cipher}d6aa219f08d23a2c5991c23d6aaa34a449fc849bc7f4217358f303cf6ffd846f
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
  instance:
    prefer-ip-address: true
